CREATE TABLE usuario (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome 		VARCHAR(255) 		NOT NULL,
	sobrenome 	VARCHAR(255) 		NOT NULL
	nome 		VARCHAR(255)		NOT NULL,
	cep 		VARCHAR(255)		NOT NULL,
	cidade  	VARCHAR(255)		NOT NULL,
	bairro		VARCHAR(255)		NOT NULL,
	logradouro 	VARCHAR(255)		NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;